// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8_1D4ZQUgcDbQ3NMzwsPnqsT2ubPcuI8',
    appId: '1:217574445417:web:034792ba59f6f6e8502df8',
    messagingSenderId: '217574445417',
    projectId: 'todo-9f3f8',
    authDomain: 'todo-9f3f8.firebaseapp.com',
    databaseURL: 'https://todo-9f3f8-default-rtdb.firebaseio.com',
    storageBucket: 'todo-9f3f8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCntoD2oj0nCaGr8xmZPdnm9Nh8WkUUKF0',
    appId: '1:217574445417:android:9ea642045aa51cbf502df8',
    messagingSenderId: '217574445417',
    projectId: 'todo-9f3f8',
    databaseURL: 'https://todo-9f3f8-default-rtdb.firebaseio.com',
    storageBucket: 'todo-9f3f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRxVwvgLMvfqDIH6uIDcMcn6tFdxIltJY',
    appId: '1:217574445417:ios:65837df5c3b4dba1502df8',
    messagingSenderId: '217574445417',
    projectId: 'todo-9f3f8',
    databaseURL: 'https://todo-9f3f8-default-rtdb.firebaseio.com',
    storageBucket: 'todo-9f3f8.appspot.com',
    iosClientId: '217574445417-86qvnipfo1s6n450tjbqdf3oed0cip82.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );
}
